### PR TITLE
Test

### PR DESCRIPTION
**Pull request by clindforsSejsing**
4 test: contact-page, login and review, routs and moviespage. 

(npm install) 
npm start and npm open 

U need a cypress.env.json te get the secret password to be able to set the password and username for login.

### CODE REVIEW

**Comment by kaulfield23** [comment]
wow! nice! I tested it with the account that you gave me but it didn't pass the login test. So I tested with my account and it works! I guess Kalle anka has wrong password or wrong id? but anyways it is really cool! especially when it writes the comment by itself and test haha XD

**Comment by kaulfield23** [comment]
I think it will be good to add readme about cypress.env.json!

**Comment by clindforsSejsing** [comment]
> I think it will be good to add readme about cypress.env.json for testing!

yeah, I´ve added some text about Cypress-test in readme in the commit "added cypress to readme" but I can look moore into it tomorrow

**Comment by kaulfield23** [comment]
> > I think it will be good to add readme about cypress.env.json for testing!
> 
> yeah, I´ve added some text about Cypress-test in readme in the commit "added cypress to readme" but I can look moore into it tomorrow

Oh sorry I missed that part!! I think that readme looks good enough!

**Comment by clindforsSejsing** [comment]
exchanged with newer pullreq feedbackform instead

**Pull request closed without merging**
