### PR TITLE
inloggning

### PR DESCRIPTION
**Pull request by kaulfield23**

### CODE REVIEW

**Comment by JohanEkstroem** [comment]
Branch appears to have merge conflicts  and i cannnot see or resolve it. "Resolve conflicts" button is gray. Take a look at CustomUI.tsx and login.tsx to figure out what causes the problem.

**Comment by JohanEkstroem** [comment]
Also consider hiding password input in login page

**Comment by kaulfield23** [comment]
> fixed merge conflict now!

**Comment by kaulfield23** [comment]
> Also consider hiding password input in login page

thanks! i will on it!

**Comment by JohanEkstroem** [comment]
cool, merge merge away

**Pull request merged**
